disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Hagfish"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Notes & thoughts"
copyright = "Copy, _right?_ :thinking_face:"

  [params.author]
  name = "Yiheng Yu"
  links = [ ]

["params.author"]
name = "Yiheng Yu"
