colorScheme = "cream"

defaultAppearance = "dark"
autoSwitchAppearance = true
enableA11y = true
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
hotlinkFeatureImage = false
fingerprintAlgorithm = "sha512"
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"
firebase = { }
fathomAnalytics = { }
umamiAnalytics = { }
selineAnalytics = { }
buymeacoffee = { }
verification = { }
rssnext = { }
advertisement = { }
highlightCurrentMenuArea = true
math = true
smartTOC = true
sitemap = { }

[header]
layout = "fixed-fill"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = true
showRecentItems = "5"
showMoreLink = true
showMoreLinkDest = "/posts"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = false
disableHeroImageFilter = false
homepageImage = "."

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = true
showAuthor = true
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = false
showTableOfContents = true
showTaxonomies = true
showCategoryOnly = false
showAuthorsBadges = false
showAuthorBottom = true
showWordCount = true
showZenMode = true
sharingLinks = [ "bluesky", "mastodon", "linkedin" ]

[list]
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
orderByWeight = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = true
cardView = false
heroStyle = "background"

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[author]
email = "yuyiheng1994@gmail.com"